# Generated by Django 4.2.1 on 2023-05-25 19:14

from django.db import migrations
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_articlepage_annotation_alter_articlepage_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="article_body",
            field=wagtail.fields.StreamField(
                [
                    ("linetext", wagtail.blocks.CharBlock()),
                    ("mtext", wagtail.blocks.TextBlock()),
                    ("richtext", wagtail.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("table", wagtail.contrib.table_block.blocks.TableBlock()),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
