# Generated by Django 4.2.1 on 2023-05-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_articlepage_article_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="search_name",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="TransName"
            ),
        ),
    ]
